### ISSUE TITLE
vp-setupfit fails because importlib.metadata.PackageNotFoundError: n3fit

### ISSUE THREAD

**Issue by flonigro** [HEP-PBSP/SIMUnet#59]
I am trying to run vp-setupfit file.yml following instructions on the Documentation page. In particular, I copied and pasted the runcard on the "simultaneous fit" example and I obtain the followin error: 
```
Traceback (most recent call last):
  File "/home/turing/miniconda3/envs/simunet/bin/n3fit", line 33, in <module>
    sys.exit(load_entry_point('n3fit', 'console_scripts', 'n3fit')())
  File "/home/turing/miniconda3/envs/simunet/bin/n3fit", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/home/turing/miniconda3/envs/simunet/lib/python3.9/importlib/metadata.py", line 542, in distribution
    return Distribution.from_name(distribution_name)
  File "/home/turing/miniconda3/envs/simunet/lib/python3.9/importlib/metadata.py", line 196, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: n3fit
```
Moreover, n3fit is correctly installed in my conda env which I have activated when I run the aforementioned runcard.

**Comment by flonigro** [comment]
Thank you @comane! Now, it works.
